version: '3'
services:
  db:
    image: postgres
    environment:
      RAILS_ENV: development
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "55432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
