version: '3'
services:
  db_mysql:
    image: "mysql:5.6.34"
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: rootpasswd
    ports:
      - "33069:3306"
    restart: always
    volumes:
      - mysql:/var/lib/mysql

#  db_postgresql:
#    image: postgres
#    volumes:
#      - ./tmp/db:/var/lib/postgresql/data
#    ports:
#      - "55432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
